### ISSUE TITLE
Wrong drive size checked (Linux)

### ISSUE THREAD

**Issue by yvlasenko** [daqnext/meson-terminal#9]
When data located on a mountpoint other than `/` service would consider root FS free bytes when started by systemd unit.

Systemd would call app by absolute path but workdir would be `/` so https://github.com/daqnext/meson-terminal/blob/f3321c5976ea514959e6fb05f8e572db295db986/terminal/manager/filemgr/filemgr.go#L82 would check `/` instead.

Suggestions:
* (very dirty) Modify systemd unit adding `WorkingDirectory=/path/to/meson_root`
* (okay-ish but dirty architecture-wise) Improve meson_root location based on binary location and check it
* (good) have `spaceholder` dir path configurable and check it explicitly since ideally data should not live with the application
    * (improvement) allow multiple data dirs to utilize spare capacity without having to use LVM or similar

Repro:
```
/ - 8Gb
/mnt - 100Gb
```

App path: `/mnt/mesos`
App config (disk space): 80Gb

`./meson service-start` would succeed but `./meson service-status` would show error and service would die.

Codeowner's take is appreciated on which solution to consider appropriate

**Comment by goodboy3** [comment]
modify disk.Usage("./") =>  disk.Usage(runpath.RunPath) 

Temporary solution: Place the app folder in the mount directory of the large hard drive.
This issue will be fixed in next version

**Comment by yvlasenko** [comment]
> Temporary solution: Place the app folder in the mount directory of the large hard drive.

That's the point, even though the app folder is located on a larger drive space validation would still fail unless systemd's working directory changed to point to it.

> modify disk.Usage("./") => disk.Usage(runpath.RunPath)

Yup, that's suggestion 2 I made. @goodboy3 want me to create a PR so that it lands in next version or you're considering any better fix?
